build:
	docker build -t mikereem/kube-frontend:1.0.0 -t mikereem/kube-frontend:latest .
build-dev:
	docker build -t mikereem/kube-frontend:dev --target dev .
push:
	docker push mikereem/kube-frontend:1.0.0
	docker push mikereem/kube-frontend:latest